### ISSUE TITLE
Error if dcpx file contains variables defined as binary/string

### ISSUE THREAD

**Issue by dev-gb** [modelica/DCPTester#3]
Test files could not be generated if a the dcpx file contains binary variables.

```
java.lang.Exception: Could not find Variable with ValueReference : 9
        at wrappers.DcpWrapper.getDataTypeFromVr(DcpWrapper.java:1554)
        at objectCreatorHelper.PayloadFieldCreator.createDefaultSendingPayloadField(PayloadFieldCreator.java:975)
        at objectCreatorHelper.TransitionCreator.createSendingDATInputOutput(TransitionCreator.java:6887)
        at testTransformer.TestTransformer.handleAddTransition(TestTransformer.java:1372)
        at testTransformer.TestTransformer.handleXmlNode(TestTransformer.java:629)
        at testTransformer.TestTransformer.handleForEach(TestTransformer.java:767)
        at testTransformer.TestTransformer.handleXmlNode(TestTransformer.java:657)
        at testTransformer.TestTransformer.handleIfItem(TestTransformer.java:1009)
        at testTransformer.TestTransformer.handleXmlNode(TestTransformer.java:650)
        at testTransformer.TestTransformer.handleForEach(TestTransformer.java:863)
        at testTransformer.TestTransformer.handleXmlNode(TestTransformer.java:657)
        at testTransformer.TestTransformer.generateFinalTestProcedure(TestTransformer.java:142)
        at main.Launcher.main(Launcher.java:282)
```

**Comment by dev-gb** [comment]
Postet the error in the wrong github project 
It's a DCPTestGenerator Bug
https://github.com/modelica/DCPTestGenerator
